# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9192
  servlet:
    context-path: /account-book
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    ##url: jdbc:mysql://47.94.217.183:3306/account_book?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://127.0.0.1:3306/account_book?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    ##password: 1qaz!QAZ
#mybatis:
#  table:
#    auto: update
#    #create	系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
#    #update	系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
#    #none 		系统不做任何处理。
#    #add		新增表/新增字段/新增索引/新增唯一约束的功能，不做做修改和删除 (只在版本1.0.9.RELEASE及以上支持)。
#  model:
#    pack: com.mgk.account.book.modules.manager.pojo #扫描用于创建表的对象的包名，多个包用“,”隔开
#  database:
#    type: mysql #数据库类型 目前只支持mysql

mybatis-plus:
  #1.如果是mybatis 直接在mybatis下增加该配置。
  #2.如果使用properties配置方式,要写成mapperLocations
  mapper-locations: classpath*:com/mgk/account/book/modules/manager/mapper/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  configuration:
    map-underscore-to-camel-case: false

# 自定义的jwt配置
jwt:
  # 过期时间：2小时
  expire: 6000000
  #7200000
  # 密钥
  secret: 6Dx8SIuaHXJYnpsG18SSpjPs50lZcT52

